# Generated by Django 5.2.17 on 2026-08-07 14:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("memberships", "0001_initial"),
        ("patterns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "等待分析"),
                            ("analyzing", "正在分析"),
                            ("awaiting_confirmation", "等待用户确认"),
                            ("quota_reserved", "已预留生成张数"),
                            ("queued", "排队中"),
                            ("generating", "生成中"),
                            ("validating", "正在校验"),
                            ("succeeded", "生成成功"),
                            ("saved", "保存成功"),
                            ("failed", "生成失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="uploaded",
                        max_length=40,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("basic", "基础生成"), ("advanced", "高级创作")],
                        default="basic",
                        max_length=20,
                    ),
                ),
                ("input_image", models.ImageField(blank=True, upload_to="creation/input/%Y/%m/")),
                ("idempotency_key", models.CharField(max_length=120)),
                ("configuration_snapshot", models.JSONField(default=dict)),
                ("current_stage", models.CharField(blank=True, max_length=80)),
                ("progress_message", models.CharField(blank=True, max_length=240)),
                ("failure_code", models.CharField(blank=True, max_length=80)),
                ("failure_message", models.CharField(blank=True, max_length=500)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quota_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="memberships.generationquotaperiod",
                    ),
                ),
                (
                    "result_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_tasks",
                        to="patterns.patternversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="GenerationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("selected_subject", models.JSONField(default=dict)),
                ("crop", models.JSONField(default=dict)),
                ("grid_size", models.PositiveSmallIntegerField(default=50)),
                ("color_limit", models.PositiveSmallIntegerField(default=24)),
                ("background_mode", models.CharField(default="simplify", max_length=20)),
                ("style", models.CharField(blank=True, max_length=80)),
                ("creative_instruction", models.TextField(blank=True)),
                ("preserve_content", models.JSONField(default=list)),
                ("editable_content", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="creation.generationtask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quality_level", models.CharField(max_length=40)),
                ("suitability_level", models.CharField(max_length=40)),
                ("primary_subject", models.CharField(blank=True, max_length=120)),
                ("subject_count", models.PositiveSmallIntegerField(default=0)),
                ("subject_region", models.JSONField(default=dict)),
                ("confidence_level", models.CharField(blank=True, max_length=20)),
                ("issues", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=dict)),
                ("requires_subject_confirmation", models.BooleanField(default=False)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("prompt_version", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="creation.generationtask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("analysis", "图片分析"),
                            ("segmentation", "主体分割"),
                            ("image_edit", "图像创作"),
                            ("visual_review", "视觉复查"),
                            ("guidance", "制作建议"),
                        ],
                        max_length=30,
                    ),
                ),
                ("provider", models.CharField(max_length=80)),
                ("model_name", models.CharField(max_length=120)),
                ("prompt_version", models.CharField(blank=True, max_length=40)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("success", models.BooleanField(default=False)),
                ("retry_number", models.PositiveSmallIntegerField(default=0)),
                ("internal_cost", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("error_type", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_calls",
                        to="creation.generationtask",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="generationtask",
            constraint=models.UniqueConstraint(
                fields=("user", "idempotency_key"), name="unique_user_generation_idempotency_key"
            ),
        ),
    ]
