# Generated by Django 5.2.17 on 2026-08-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageanalysisresult",
            name="subject_mask",
            field=models.ImageField(blank=True, upload_to="creation/masks/%Y/%m/"),
        ),
    ]
