# Generated by Django 5.2.17 on 2026-08-07 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creation", "0002_imageanalysisresult_subject_mask"),
        ("patterns", "0002_pattern_is_saved"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvancedCreationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("style_transfer", "风格转换"),
                            ("background_creation", "背景创作"),
                            ("contour_enhance", "主体轮廓强化"),
                            ("element_edit", "元素增删"),
                            ("local_edit", "局部编辑"),
                        ],
                        max_length=40,
                    ),
                ),
                ("instruction", models.TextField(blank=True)),
                ("preserve_content", models.JSONField(default=list)),
                ("editable_content", models.JSONField(default=list)),
                ("edit_region", models.JSONField(default=dict)),
                ("review_result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advanced_requests",
                        to="patterns.patternversion",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advanced_request",
                        to="creation.generationtask",
                    ),
                ),
            ],
        ),
    ]
