# Generated by Django 5.2.17 on 2026-08-07 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creation", "0003_advancedcreationrequest"),
        ("memberships", "0001_initial"),
        ("patterns", "0004_pattern_pattern_owner_library"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="generationtask",
            index=models.Index(
                fields=["user", "status", "-created_at"], name="task_user_status_created"
            ),
        ),
        migrations.AddIndex(
            model_name="generationtask",
            index=models.Index(fields=["status", "-created_at"], name="task_status_created"),
        ),
        migrations.AddIndex(
            model_name="modelcalllog",
            index=models.Index(
                fields=["capability", "success", "-created_at"], name="model_call_cap_success"
            ),
        ),
    ]
