# Generated by Django 5.2.17 on 2026-08-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0004_generationtask_task_user_status_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationsettings',
            name='face_mode',
            field=models.CharField(default='composition', max_length=30),
        ),
        migrations.AddField(
            model_name='generationsettings',
            name='grid_height',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationsettings',
            name='grid_width',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
