# Generated by Django 5.2.17 on 2026-08-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0005_v2_pattern_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationsettings',
            name='finished_use',
            field=models.CharField(default='unsure', max_length=30),
        ),
    ]
