# Generated by Django 5.2.17 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creation", "0006_v2_ironing_guidance"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationsettings",
            name="ironing_style",
            field=models.CharField(default="standard_two_sided", max_length=40),
        ),
    ]
