# Generated by Django 5.2.17 on 2026-08-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_guest",
            field=models.BooleanField(default=False),
        ),
    ]
