# Generated by Django 5.2.17 on 2026-08-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile_is_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="accounts/avatars/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_background_mode",
            field=models.CharField(default="simplify", max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_color_limit",
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_finished_use",
            field=models.CharField(default="unsure", max_length=30),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_pattern_size",
            field=models.CharField(default="58x58", max_length=12),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(default="zh-Hans", max_length=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="remember_creation_parameters",
            field=models.BooleanField(default=True),
        ),
    ]
