"""User-selectable, community-used bead ironing effects.

Only the regular and baking-paper guidance is a standard baseline.  The other
effects are intentionally labelled as community techniques: they are visual
choices, not a manufacturer-standard instruction set.
"""

_COMMUNITY_SOURCE = "https://pindouai.app/blog/6-ironing-styles"

IRONING_STYLES = {
    "regular": {
        "code": "regular",
        "name": "常规烫",
        "effect": "平整、连接牢靠，保留清晰的拼豆颗粒感。",
        "best_for": "所有图案；第一次制作、人物和细节图优先选它。",
        "reason": "最容易判断熟度，也最适合作为第一次作品的安全起点。",
        "materials": "熨斗、烘焙纸或专用烫纸、平整耐热桌面、厚书。",
        "steps": "中温、关闭蒸汽，隔纸缓慢画小圈；豆子刚连接就停，冷却后再翻面短烫。",
        "safety": "先用边角小样确认温度；儿童请由成年人完成熨烫。",
        "source_url": "https://perler.com/blogs/projects/standard-fusing-method",
        "source_label": "查看常规烫真实案例与基础说明",
        "case_image_url": "https://pindouai.app/images/changguitang.jpg",
        "case_caption": "真实案例：常规烫效果（PindouAI 收录的社群案例）",
        "case_source_url": _COMMUNITY_SOURCE,
        "case_source_label": "案例来源：PindouAI",
        "model_class": "regular",
    },
    "waffle": {
        "code": "waffle",
        "name": "华夫格烫",
        "effect": "留下规整的格纹压印，画面会出现类似华夫格的明暗起伏。",
        "best_for": "衣服、背景墙、几何图案和需要网格光影的局部。",
        "reason": "它强调纹理而非更牢固；适合已经确定要做格纹效果的作品。",
        "materials": "熨斗、耐热格纹材质、烘焙纸、平整耐热桌面。",
        "steps": "先以常规烫把作品固定；隔烘焙纸轻压出纹理，小样成功后再处理整张。",
        "safety": "材质纹理、厚度和温度差异很大，必须先小样测试；不要直接接触熨斗。",
        "source_url": _COMMUNITY_SOURCE,
        "source_label": "查看华夫格／格纹烫真实案例",
        "case_image_url": "https://pindouai.app/images/xishangewentang.jpg",
        "case_caption": "真实案例：细闪格纹效果（社群格纹烫案例）",
        "case_source_url": _COMMUNITY_SOURCE,
        "case_source_label": "案例来源：PindouAI",
        "model_class": "waffle",
    },
    "towel": {
        "code": "towel",
        "name": "毛巾烫",
        "effect": "压出柔软、蓬松的毛绒感，边缘不再那么硬朗。",
        "best_for": "Q 版人物、萌宠、玩偶和想要柔软氛围的图案。",
        "reason": "用纹理换取可爱氛围，适合不依赖极锐利轮廓的作品。",
        "materials": "纯棉厚毛巾、烘焙纸、熨斗、平整耐热桌面。",
        "steps": "先做小样；毛巾垫在烘焙纸下方，低到中温短时熨烫，微温时揭开。",
        "safety": "毛巾厚度会改变受热速度，停留过久容易粘连或变形。",
        "source_url": _COMMUNITY_SOURCE,
        "source_label": "查看毛巾烫真实案例",
        "case_image_url": "https://pindouai.app/images/maojintang.jpg",
        "case_caption": "真实案例：毛巾烫效果（PindouAI 收录的社群案例）",
        "case_source_url": _COMMUNITY_SOURCE,
        "case_source_label": "案例来源：PindouAI",
        "model_class": "towel",
    },
    "bathcloth": {
        "code": "bathcloth",
        "name": "澡巾烫",
        "effect": "形成粗颗粒、凹凸明显的做旧质感。",
        "best_for": "面包甜点、复古物件、石头、木头和粗犷主题。",
        "reason": "纹理辨识度很高，但会弱化小尺寸的人脸与细线。",
        "materials": "干净澡巾、烘焙纸、熨斗、平整耐热桌面。",
        "steps": "隔烘焙纸轻压，先完成小样再决定是否加深纹理；一次只处理一小段。",
        "safety": "粗纹会放大受热不均，人物脸部、文字和很小的细节不建议使用。",
        "source_url": "https://yeshengdou.com/",
        "source_label": "查看澡巾烫真实案例",
        "case_image_url": "https://yeshengdou.com/images/works/%E6%BE%A1%E5%B7%BE%E7%83%AB.jpg",
        "case_caption": "真实案例：澡巾烫作品（野生豆作品展示）",
        "case_source_url": "https://yeshengdou.com/",
        "case_source_label": "案例来源：野生豆",
        "model_class": "bathcloth",
    },
    "baking_paper": {
        "code": "baking_paper",
        "name": "烘焙纸烫",
        "effect": "表面干净平整，是最容易复刻的基础熨烫保护层。",
        "best_for": "所有图案；特别适合新手、人物细节与需要平整成品的作品。",
        "reason": "烘焙纸耐热且不易粘连，是稳定完成第一张作品的默认工具。",
        "materials": "烘焙纸、熨斗、平整耐热桌面、厚书。",
        "steps": "覆盖烘焙纸后以中温、无蒸汽缓慢画圈；冷却后再移动作品。",
        "safety": "只使用烘焙纸或专用烫纸，不要用蜡纸；熨斗不要停在同一处。",
        "source_url": "https://perler.com/blogs/projects/standard-fusing-method",
        "source_label": "查看烘焙纸基础熨烫说明",
        "case_image_url": "https://perler.com/cdn/shop/articles/perler-project_standard-fusing-method-01_db439831-2f30-4145-8c4d-952c1d2419cc.jpg?v=1760542077&width=1500",
        "case_caption": "真实案例：烘焙纸基础熔合（Perler 官方项目）",
        "case_source_url": "https://perler.com/blogs/projects/standard-fusing-method",
        "case_source_label": "案例来源：Perler 官方",
        "model_class": "baking-paper",
    },
    "glitter": {
        "code": "glitter",
        "name": "格里特烫",
        "effect": "闪面与光点会被放大，成品有更强的梦幻反光。",
        "best_for": "星空、透明豆、魔法道具、首饰感配件和高光区域。",
        "reason": "为闪亮氛围而选；适合需要视觉焦点的图案，不是人物细节的默认方案。",
        "materials": "格里特纹理材料、烘焙纸、熨斗、平整耐热桌面。",
        "steps": "先小样确认温度；隔纸短时熨烫，稍微放凉再揭开，观察闪面是否完整。",
        "safety": "温度过高会损伤透明或闪面豆；不要把纹理材料直接贴在熨斗底板上。",
        "source_url": "https://yeshengdou.com/",
        "source_label": "查看格里特烫真实案例",
        "case_image_url": "https://yeshengdou.com/images/works/%E6%A0%BC%E5%88%A9%E7%89%B9%E7%B2%97%E9%97%AA%E7%83%AB%E6%9E%9C%E7%AF%AE.jpg",
        "case_caption": "真实案例：格利特粗闪烫果篮（野生豆作品展示）",
        "case_source_url": "https://yeshengdou.com/",
        "case_source_label": "案例来源：野生豆",
        "model_class": "glitter",
    },
}


def get_ironing_style(code: str) -> dict:
    """Return the safe regular baseline for old or unknown saved versions."""
    return IRONING_STYLES.get(code, IRONING_STYLES["regular"])
