# Generated by Django 5.2.17 on 2026-08-07 14:44

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("basic_generation", "基础生成"),
                            ("style_transfer", "风格转换"),
                            ("multi_subject", "多主体处理"),
                            ("composition", "构图调整"),
                            ("background_creation", "背景创作"),
                            ("element_edit", "元素增删"),
                            ("local_edit", "局部重绘"),
                            ("advanced_guidance", "高级制作辅助"),
                        ],
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=240)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="GenerationQuotaPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("total_limit", models.PositiveIntegerField()),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("reserved_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_quota_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GenerationQuotaLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task_reference", models.UUIDField(blank=True, null=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("allocate", "发放"),
                            ("reserve", "预留"),
                            ("consume", "使用"),
                            ("release", "释放"),
                            ("adjust", "后台调整"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                ("reason", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quota_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quota_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="memberships.generationquotaperiod",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("visitor", "免费游客"),
                            ("registered", "注册会员"),
                            ("plus", "Plus 会员"),
                            ("pro", "Pro 会员"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("price_display", models.CharField(blank=True, max_length=80)),
                (
                    "quota_period",
                    models.CharField(
                        choices=[("lifetime", "一次性"), ("monthly", "每月")],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("generation_limit", models.PositiveIntegerField(default=0)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("allow_advanced_trial", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "features",
                    models.ManyToManyField(
                        blank=True, related_name="plans", to="memberships.feature"
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "id"),
            },
        ),
        migrations.AddField(
            model_name="generationquotaperiod",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quota_periods",
                to="memberships.membershipplan",
            ),
        ),
        migrations.CreateModel(
            name="MembershipSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="memberships.membershipplan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="generationquotaperiod",
            constraint=models.UniqueConstraint(
                fields=("user", "starts_at"), name="unique_user_quota_period_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="generationquotaperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("used_count__gte", 0)), name="quota_used_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="generationquotaperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_count__gte", 0)), name="quota_reserved_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="generationquotaperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total_limit__gte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("used_count"), "+", models.F("reserved_count")
                        ),
                    )
                ),
                name="quota_usage_within_limit",
            ),
        ),
    ]
