# Generated by Django 5.2.17 on 2026-08-07 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Palette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("version", models.CharField(default="1", max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="Pattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patterns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PaletteColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=80)),
                ("red", models.PositiveSmallIntegerField()),
                ("green", models.PositiveSmallIntegerField()),
                ("blue", models.PositiveSmallIntegerField()),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "palette",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colors",
                        to="patterns.palette",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "code"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("palette", "code"), name="unique_palette_color_code"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PatternVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("source_image", models.ImageField(blank=True, upload_to="patterns/source/%Y/%m/")),
                (
                    "creative_base_image",
                    models.ImageField(blank=True, upload_to="patterns/base/%Y/%m/"),
                ),
                (
                    "effect_preview",
                    models.ImageField(blank=True, upload_to="patterns/effect/%Y/%m/"),
                ),
                ("grid_preview", models.ImageField(blank=True, upload_to="patterns/grid/%Y/%m/")),
                ("grid_data", models.JSONField(default=dict)),
                ("material_counts", models.JSONField(default=dict)),
                ("settings_snapshot", models.JSONField(default=dict)),
                ("validation_result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_versions",
                        to="patterns.patternversion",
                    ),
                ),
                (
                    "pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="patterns.pattern",
                    ),
                ),
            ],
            options={
                "ordering": ("pattern", "version_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pattern", "version_number"), name="unique_pattern_version_number"
                    )
                ],
            },
        ),
    ]
