# Generated by Django 5.2.17 on 2026-08-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patterns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pattern",
            name="is_saved",
            field=models.BooleanField(default=False),
        ),
    ]
