# Generated by Django 5.2.17 on 2026-08-07 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patterns", "0002_pattern_is_saved"),
    ]

    operations = [
        migrations.AddField(
            model_name="pattern",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PatternExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("effect_png", "效果图 PNG"),
                            ("grid_png", "编号网格 PNG"),
                            ("pattern_pdf", "制作图 PDF"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="patterns/exports/%Y/%m/")),
                ("page_count", models.PositiveSmallIntegerField(default=1)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="patterns.patternversion",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("version", "kind"), name="unique_version_export_kind"
                    )
                ],
            },
        ),
    ]
