# Generated by Django 5.2.17 on 2026-08-07 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patterns", "0003_pattern_deleted_at_patternexport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pattern",
            index=models.Index(
                fields=["owner", "is_saved", "deleted_at", "-updated_at"],
                name="pattern_owner_library",
            ),
        ),
    ]
