# Generated by Django 5.2.17 on 2026-08-09 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_categories(apps, schema_editor):
    category = apps.get_model("patterns", "DefaultPatternCategory")
    category.objects.bulk_create(
        [
            category(code="people", name="人物", sort_order=10),
            category(code="pets", name="宠物", sort_order=20),
            category(code="anime", name="动漫", sort_order=30),
            category(code="objects", name="物品", sort_order=40),
            category(code="scenery", name="风景", sort_order=50),
            category(code="text", name="文字", sort_order=60),
            category(code="other", name="其他", sort_order=70, is_fallback=True),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("patterns", "0004_pattern_pattern_owner_library"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultPatternCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=40)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_fallback", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("sort_order", "code"),
            },
        ),
        migrations.CreateModel(
            name="PatternCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_fallback", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pattern_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.AddField(
            model_name="pattern",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patterns",
                to="patterns.patterncategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="patterncategory",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_user_pattern_category"
            ),
        ),
        migrations.RunPython(create_default_categories, migrations.RunPython.noop),
    ]
