# Generated by Django 5.2.17 on 2026-08-07 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="configurationrevision",
            index=models.Index(
                fields=["namespace", "key", "is_active", "-version"], name="config_active_revision"
            ),
        ),
    ]
